version: '3.9'

services:
  php8-1:
    build: ./8.1-fpm-alpine
    image: ghcr.io/erkenes/php:8.1-fpm-alpine

  php8-2:
    build: ./8.2-fpm-alpine
    image: ghcr.io/erkenes/php:8.2-fpm-alpine

  php8-3:
    build: ./8.3-fpm-alpine
    image: ghcr.io/erkenes/php:8.3-fpm-alpine

  php8-4:
    build: ./8.4-fpm-alpine
    image: ghcr.io/erkenes/php:8.4-fpm-alpine
